---
- name: Install Hybrid AI Flow
  hosts: localhost

  vars:
    install: false
    apps: ["training", "app"]

  tasks:
    - include_tasks: storage.yaml
      when: storage

    - include_tasks: project.yaml

    - name: Build project
      shell: mvn clean package

    - name: Apply manifests
      shell: oc apply -f {{ item }}/target/kubernetes/openshift.yml
      loop: "{{ apps }}"

    - name: Build
      shell: oc start-build {{ item }} --from-file=training/target/{{ item }}-1.0-runner.jar --follow
      loop: "{{ apps }}"